--- *** --- join_inference --- *** ---

2026-06-110:02:20,22[PREFILTER] 6columns -> 5kept (removed)

--- *** --- taille candidates : 39--- *** ---

AdventureWorks_Customer_Lookup.BirthDate -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Customer_Lookup.EducationLevel -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Customer_Lookup.FirstName -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Customer_Lookup.Gender -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Customer_Lookup.HomeOwner -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Customer_Lookup.LastName -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Customer_Lookup.MaritalStatus -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Customer_Lookup.Occupation -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Customer_Lookup.Prefix -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Product_Categories_Lookup.CategoryName -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Product_Lookup.ModelName -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Product_Lookup.ProductColor -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Product_Lookup.ProductDescription -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Product_Lookup.ProductName -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Product_Lookup.ProductSKU -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Product_Lookup.ProductSize -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Product_Lookup.ProductStyle -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Product_Subcategories_Lookup.SubcategoryName -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Returns_Data.ReturnDate -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Territory_Lookup.Continent -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Territory_Lookup.Country -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Territory_Lookup.Region -> AdventureWorks_Calendar_Lookup.Date | ratio=1.0
AdventureWorks_Product_Categories_Lookup.ProductCategoryKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductSubcategoryKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Product_Subcategories_Lookup.ProductCategoryKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Returns_Data.ProductKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Returns_Data.ReturnQuantity -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Returns_Data.TerritoryKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2020.CustomerKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderLineItem -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderQuantity -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2020.ProductKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2020.TerritoryKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2021.CustomerKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderLineItem -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderQuantity -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2021.ProductKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2021.TerritoryKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2022.CustomerKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderLineItem -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderQuantity -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2022.ProductKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2022.TerritoryKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Territory_Lookup.SalesTerritoryKey -> AdventureWorks_Customer_Lookup.CustomerKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductSubcategoryKey -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Product_Subcategories_Lookup.ProductCategoryKey -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Returns_Data.ProductKey -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Returns_Data.ReturnQuantity -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Returns_Data.TerritoryKey -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.CustomerKey -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderLineItem -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderQuantity -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.ProductKey -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.TerritoryKey -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.CustomerKey -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderLineItem -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderQuantity -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.ProductKey -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.TerritoryKey -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.CustomerKey -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderLineItem -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderQuantity -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.ProductKey -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.TerritoryKey -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Territory_Lookup.SalesTerritoryKey -> AdventureWorks_Product_Categories_Lookup.ProductCategoryKey | ratio=1.0
AdventureWorks_Product_Categories_Lookup.ProductCategoryKey -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Product_Subcategories_Lookup.ProductCategoryKey -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Returns_Data.ProductKey -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Returns_Data.ReturnQuantity -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Returns_Data.TerritoryKey -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.CustomerKey -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderLineItem -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderQuantity -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.ProductKey -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.TerritoryKey -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.CustomerKey -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderLineItem -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderQuantity -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.ProductKey -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.TerritoryKey -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.CustomerKey -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderLineItem -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderQuantity -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.ProductKey -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.TerritoryKey -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Territory_Lookup.SalesTerritoryKey -> AdventureWorks_Product_Lookup.ProductKey | ratio=1.0
AdventureWorks_Product_Categories_Lookup.ProductCategoryKey -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductSubcategoryKey -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Returns_Data.ProductKey -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Returns_Data.ReturnQuantity -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Returns_Data.TerritoryKey -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.CustomerKey -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderLineItem -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderQuantity -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.ProductKey -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.TerritoryKey -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.CustomerKey -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderLineItem -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderQuantity -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.ProductKey -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.TerritoryKey -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.CustomerKey -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderLineItem -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderQuantity -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.ProductKey -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.TerritoryKey -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Territory_Lookup.SalesTerritoryKey -> AdventureWorks_Product_Subcategories_Lookup.ProductSubcategoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, CustomerKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, CustomerKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, CustomerKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, CustomerKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, OrderLineItem, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, OrderLineItem, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, OrderLineItem, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, OrderLineItem, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, OrderQuantity, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, OrderQuantity, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, OrderQuantity, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, OrderQuantity, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, ProductKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, ProductKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, ProductKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, ProductKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, TerritoryKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, TerritoryKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, TerritoryKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, TerritoryKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, CustomerKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, CustomerKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, CustomerKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, CustomerKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, OrderLineItem, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, OrderLineItem, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, OrderLineItem, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, OrderLineItem, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, OrderQuantity, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, OrderQuantity, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, OrderQuantity, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, OrderQuantity, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, ProductKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, ProductKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, ProductKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, ProductKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, TerritoryKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, TerritoryKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, TerritoryKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, TerritoryKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, CustomerKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, CustomerKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, CustomerKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, CustomerKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, OrderLineItem, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, OrderLineItem, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, OrderLineItem, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, OrderLineItem, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, OrderQuantity, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, OrderQuantity, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, OrderQuantity, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, OrderQuantity, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, ProductKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, ProductKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, ProductKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, ProductKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, TerritoryKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, TerritoryKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, TerritoryKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, TerritoryKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, CustomerKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, CustomerKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, CustomerKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, CustomerKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, OrderLineItem, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, OrderLineItem, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, OrderLineItem, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, OrderLineItem, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, OrderQuantity, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, OrderQuantity, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, OrderQuantity, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, OrderQuantity, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, ProductKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, ProductKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, ProductKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, ProductKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, TerritoryKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, TerritoryKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, TerritoryKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, TerritoryKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, CustomerKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, CustomerKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, CustomerKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, CustomerKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, OrderLineItem, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, OrderLineItem, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, OrderLineItem, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, OrderLineItem, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, OrderQuantity, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, OrderQuantity, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, OrderQuantity, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, OrderQuantity, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, TerritoryKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, TerritoryKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, TerritoryKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, TerritoryKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, CustomerKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, CustomerKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, CustomerKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, CustomerKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, OrderLineItem, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, OrderLineItem, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, OrderLineItem, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, OrderLineItem, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, OrderQuantity, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, OrderQuantity, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, OrderQuantity, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, OrderQuantity, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, ProductKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, ProductKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, ProductKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, ProductKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, TerritoryKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, TerritoryKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, TerritoryKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, TerritoryKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, CustomerKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, CustomerKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, CustomerKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, CustomerKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, OrderLineItem, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, OrderLineItem, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, OrderLineItem, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, OrderLineItem, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, OrderQuantity, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, OrderQuantity, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, OrderQuantity, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, OrderQuantity, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, ProductKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, ProductKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, ProductKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, ProductKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, TerritoryKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, TerritoryKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, TerritoryKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, TerritoryKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, CustomerKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, CustomerKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, CustomerKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, CustomerKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, OrderLineItem, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, OrderLineItem, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, OrderLineItem, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, OrderLineItem, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, OrderQuantity, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, OrderQuantity, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, OrderQuantity, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, OrderQuantity, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, ProductKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, ProductKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, ProductKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, ProductKey, TerritoryKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, TerritoryKey, CustomerKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, TerritoryKey, OrderLineItem -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, TerritoryKey, OrderQuantity -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, TerritoryKey, ProductKey -> AdventureWorks_Returns_Data.ReturnDate, ProductKey, TerritoryKey | ratio=1.0
AdventureWorks_Product_Categories_Lookup.ProductCategoryKey -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductSubcategoryKey -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Product_Subcategories_Lookup.ProductCategoryKey -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Returns_Data.ProductKey -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Returns_Data.ReturnQuantity -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Returns_Data.TerritoryKey -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2021.CustomerKey -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderLineItem -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderQuantity -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2021.ProductKey -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2021.TerritoryKey -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2022.CustomerKey -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderLineItem -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderQuantity -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2022.ProductKey -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Sales_Data_2022.TerritoryKey -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Territory_Lookup.SalesTerritoryKey -> AdventureWorks_Sales_Data_2020.CustomerKey | ratio=1.0
AdventureWorks_Product_Categories_Lookup.CategoryName, ProductCategoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Lookup.ModelName, ProductSubcategoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductColor, ProductSubcategoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductDescription, ProductSubcategoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductName, ProductSubcategoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductSKU, ProductSubcategoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductSize, ProductSubcategoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductStyle, ProductSubcategoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Subcategories_Lookup.SubcategoryName, ProductCategoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Returns_Data.ReturnDate, ProductKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Returns_Data.ReturnDate, ReturnQuantity -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Returns_Data.ReturnDate, TerritoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, CustomerKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, OrderLineItem -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, OrderQuantity -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, ProductKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, TerritoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, CustomerKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, OrderLineItem -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, OrderQuantity -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, ProductKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, TerritoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, CustomerKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, OrderLineItem -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, OrderQuantity -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, ProductKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, TerritoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, CustomerKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, OrderLineItem -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, OrderQuantity -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, ProductKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderDate, TerritoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, CustomerKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, OrderLineItem -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, OrderQuantity -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, ProductKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2022.StockDate, TerritoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Territory_Lookup.Continent, SalesTerritoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Territory_Lookup.Country, SalesTerritoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Territory_Lookup.Region, SalesTerritoryKey -> AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Categories_Lookup.CategoryName, ProductCategoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Lookup.ModelName, ProductSubcategoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductColor, ProductSubcategoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductDescription, ProductSubcategoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductName, ProductSubcategoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductSKU, ProductSubcategoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductSize, ProductSubcategoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductStyle, ProductSubcategoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Subcategories_Lookup.SubcategoryName, ProductCategoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Returns_Data.ReturnDate, ProductKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Returns_Data.ReturnDate, ReturnQuantity -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Returns_Data.ReturnDate, TerritoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, CustomerKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, OrderLineItem -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, OrderQuantity -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, ProductKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderDate, TerritoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, CustomerKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, OrderLineItem -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, OrderQuantity -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, ProductKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderNumber, TerritoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, CustomerKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, OrderLineItem -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, OrderQuantity -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, ProductKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2020.StockDate, TerritoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, CustomerKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, OrderLineItem -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, OrderQuantity -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, ProductKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderDate, TerritoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, CustomerKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, OrderLineItem -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, OrderQuantity -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, ProductKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderNumber, TerritoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, CustomerKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, OrderLineItem -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, OrderQuantity -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, ProductKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Sales_Data_2021.StockDate, TerritoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Territory_Lookup.Continent, SalesTerritoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Territory_Lookup.Country, SalesTerritoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Territory_Lookup.Region, SalesTerritoryKey -> AdventureWorks_Sales_Data_2022.OrderNumber, ProductKey | ratio=1.0
AdventureWorks_Product_Categories_Lookup.ProductCategoryKey -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Product_Lookup.ProductSubcategoryKey -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Product_Subcategories_Lookup.ProductCategoryKey -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Returns_Data.ProductKey -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Returns_Data.ReturnQuantity -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Returns_Data.TerritoryKey -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.CustomerKey -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderLineItem -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.OrderQuantity -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.ProductKey -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2020.TerritoryKey -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.CustomerKey -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderLineItem -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.OrderQuantity -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.ProductKey -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2021.TerritoryKey -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.CustomerKey -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderLineItem -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.OrderQuantity -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.ProductKey -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0
AdventureWorks_Sales_Data_2022.TerritoryKey -> AdventureWorks_Territory_Lookup.SalesTerritoryKey | ratio=1.0

--- *** --- adjacency --- *** --- time: 0:00:03.00024(absolute: 0:00:03.000240)